INSERT INTO HUMAN (DISCRIMINATOR,CPF,BIRTHDATE,FIRST_NAME,LAST_NAME, TREATMENT, GENDER, NEIGHBORHOOD, STREET, ZIP_CODE, CITY, STATE, HOME_PHONE, CELL_PHONE, EMAIL) VALUES ('patient','12313513','1991-12-19','Leonardo', 'Rogerio', 'Sr.', 0,'Bairro Um','Rua Um','0229-932','São Paulo','São Paulo','1133229292','1191828394','leo@email.com');
INSERT INTO HUMAN (DISCRIMINATOR,CPF,BIRTHDATE,FIRST_NAME,LAST_NAME, TREATMENT, GENDER, NEIGHBORHOOD, STREET, ZIP_CODE, CITY, STATE, HOME_PHONE, CELL_PHONE, EMAIL) VALUES ('patient','98713513','1991-12-19','Ricardo', 'Lima Dutra', 'Sr.', 0,'Bairro Dois','Rua Dois','9287-932','São Paulo','Terra Preta','1118229292','1180828394','ricardo@email.com');
INSERT INTO HUMAN (DISCRIMINATOR,BIRTHDATE,FIRST_NAME,LAST_NAME, TREATMENT, GENDER, NEIGHBORHOOD, STREET, ZIP_CODE, CITY, STATE, HOME_PHONE, CELL_PHONE, EMAIL, CRN) VALUES ('nutritionist','1985-01-03','Deborah', 'Moraes', 'Srta.', 1,'Bairro Três','Rua Três','0999-252','São Paulo','São Paulo','1178192929','112719292', 'deborah@email.com','1919321');
INSERT INTO HUMAN (DISCRIMINATOR,BIRTHDATE,FIRST_NAME,LAST_NAME, TREATMENT, GENDER, NEIGHBORHOOD, STREET, ZIP_CODE, CITY, STATE, HOME_PHONE, CELL_PHONE, EMAIL, CRN) VALUES ('nutritionist','1985-01-03','Renato', 'Alves', 'Sr.', 0,'Bairro Quatro','Rua Quatro','0167-132','São Paulo','São Paulo','117999292','117128394', 'renato@email.com', '772123');

INSERT INTO HUMAN_PREFERENCE (HUMAN_ID, FOOD_ID) VALUES (1,402);
INSERT INTO HUMAN_PREFERENCE (HUMAN_ID, FOOD_ID) VALUES (1,542);
INSERT INTO HUMAN_PREFERENCE (HUMAN_ID, FOOD_ID) VALUES (1,124);
INSERT INTO HUMAN_PREFERENCE (HUMAN_ID, FOOD_ID) VALUES (2,272);
INSERT INTO HUMAN_PREFERENCE (HUMAN_ID, FOOD_ID) VALUES (2,9);
INSERT INTO HUMAN_PREFERENCE (HUMAN_ID, FOOD_ID) VALUES (2,121);

INSERT INTO HUMAN_RESTRICTION (HUMAN_ID, FOOD_ID) VALUES (1,22);
INSERT INTO HUMAN_RESTRICTION (HUMAN_ID, FOOD_ID) VALUES (1,33);
INSERT INTO HUMAN_RESTRICTION (HUMAN_ID, FOOD_ID) VALUES (1,44);
INSERT INTO HUMAN_RESTRICTION (HUMAN_ID, FOOD_ID) VALUES (2,99);
INSERT INTO HUMAN_RESTRICTION (HUMAN_ID, FOOD_ID) VALUES (2,192);
INSERT INTO HUMAN_RESTRICTION (HUMAN_ID, FOOD_ID) VALUES (2,1);