/* Alimentos e suas propriedades */

SELECT FOOD.ID,
       FOOD.NAME,
       NUTRIFACT.NAME,
       NUTRIFACT.MEASURE_UNIT,
       FOOD_NUTRIFACT.VALUE
FROM FOOD, FOOD_NUTRIFACT, NUTRIFACT
WHERE FOOD.ID = [ID_DO_ALIMENTO]
AND FOOD.ID = FOOD_NUTRIFACT.FOOD_ID
AND NUTRIFACT.NAME = FOOD_NUTRIFACT.NUTRI_FACTS_KEY;

/* Alimento e sua porção base */

SELECT FOOD.ID,
       FOOD.NAME,
       PORTION_VALUE,
       MEASURE_UNIT
FROM FOOD
WHERE FOOD.ID = [ID_DO_ALIMENTO];

/* Alimento e suas medidas */

SELECT FOOD.ID,
       FOOD.NAME,
       HOMEMADE_MEASURE.NAME,
       MEASURE.VALUE_IN_PORTION
FROM FOOD, MEASURE, HOMEMADE_MEASURE
WHERE FOOD.ID = [ID_DO_ALIMENTO]
AND FOOD.ID = MEASURE.FOOD_ID
AND HOMEMADE_MEASURE.ID = MEASURE.HOMEMADE_MEASURE_ID

/* Alimentos por Categoria */

SELECT FOOD_CATEGORY.NAME,
       COUNT(*)
FROM FOOD_CATEGORY, FOOD
WHERE FOOD.CATEGORY_ID = FOOD_CATEGORY.ID
GROUP BY FOOD_CATEGORY.NAME;

/* Cardápio e seus alimentos por período de alimentação */

SELECT MENU.ID,
       MENU_CONTENT.MEAL_TYPE,
       FOOD.NAME,
       MENU_CONTENT_FOOD.PORTION_QUANTITY
FROM
       MENU,
       MENU_CONTENT,
       MENU_CONTENT_FOOD,
       FOOD
WHERE  MENU.ID = [ID_DO_CARDAPIO]
AND    MENU_CONTENT.MENU_ID = MENU.ID
AND    MENU_CONTENT_FOOD.MENU_CONTENT_ID = MENU_CONTENT.ID
AND    FOOD.ID = MENU_CONTENT_FOOD.FOOD_ID;

/* Todos os cardápios e seus donos */

/* TODO */

/* Cardápios que são template */

SELECT *
FROM
    MENU,
    MENU_TEMPLATE
WHERE MENU.ID = MENU_TEMPLATE.ID

/* Humanos e Usuários */

SELECT HUMAN.TREATMENT,
       HUMAN.FIRST_NAME,
       HUMAN.LAST_NAME,
       USER.USERNAME,
       USER.ROLE
FROM HUMAN, USER
WHERE HUMAN.ID = USER.HUMAN_ID;

/* Histórico de medidas */

SELECT HUMAN.TREATMENT,
       HUMAN.FIRST_NAME,
       HUMAN.LAST_NAME,
       HUMAN_FEATURE.*
FROM HUMAN, HUMAN_FEATURE
WHERE HUMAN.ID = HUMAN_FEATURE.HUMAN_ID
ORDER BY HUMAN_FEATURE.HUMAN_ID ASC, HUMAN_FEATURE.DATE DESC;

/* Humanos e suas preferências */

SELECT HUMAN.ID,
       HUMAN.DISCRIMINATOR,
       HUMAN.FIRST_NAME,
       FOOD.NAME
FROM FOOD, HUMAN, HUMAN_PREFERENCE
WHERE HUMAN_PREFERENCE.FOOD_ID = FOOD.ID
AND HUMAN.ID = HUMAN_PREFERENCE.HUMAN_ID;

/* Humanos e suas restrições */

SELECT HUMAN.ID,
       HUMAN.DISCRIMINATOR,
       HUMAN.FIRST_NAME,
       FOOD.NAME
FROM FOOD, HUMAN, HUMAN_RESTRICTION
WHERE HUMAN_RESTRICTION.FOOD_ID = FOOD.ID
AND HUMAN.ID = HUMAN_RESTRICTION.HUMAN_ID;

/* Parametros dinâmicos */

SELECT
    PARAMETER_CATEGORY.NAME,
    PARAMETER.NAME,
    PARAMETER.TYPE
FROM
    PARAMETER_CATEGORY
LEFT JOIN PARAMETER ON PARAMETER.ID
WHERE PARAMETER.CATEGORY_ID = PARAMETER_CATEGORY.ID

/* Parametros dado uma Feature */

SELECT DISTINCT
    PARAMETER.NAME,
    PARAMETER.TYPE,
    PARAMETER_CATEGORY.NAME,
    PARAMETER_VALUE.INTEGER_VALUE,
    PARAMETER_VALUE.BOOLEAN_VALUE,
    PARAMETER_VALUE.STRING_VALUE,
    PARAMETER_VALUE.DATE_VALUE,
    PARAMETER_VALUE.DOUBLE_VALUE
FROM
    PARAMETER,
    PARAMETER_VALUE,
    PARAMETER_CATEGORY
WHERE PARAMETER_VALUE.FEATURE_ID = [ID_DA_FEATURE]
AND PARAMETER.ID = PARAMETER_VALUE.PARAMETER_ID
AND PARAMETER.CATEGORY_ID = PARAMETER_CATEGORY.ID
ORDER BY PARAMETER_CATEGORY.NAME ASC;

/* Todos os parametros de todas as features */

SELECT
    HUMAN_FEATURE.ID as FEATURE_ID,
    HUMAN_FEATURE.DATE,
    PARAMETER.TYPE,
    PARAMETER_VALUE.DOUBLE_VALUE,
    PARAMETER_VALUE.INTEGER_VALUE,
    PARAMETER_VALUE.DATE_VALUE,
    PARAMETER_VALUE.BOOLEAN_VALUE,
    PARAMETER_VALUE.STRING_VALUE
FROM
    HUMAN_FEATURE,
    PARAMETER_VALUE,
    PARAMETER
WHERE HUMAN_FEATURE.ID = PARAMETER_VALUE.FEATURE_ID
AND PARAMETER_VALUE.PARAMETER_ID = PARAMETER.ID

/* Alimentos alergênicos */

SELECT FOOD.NAME,
       ALLERGEN_CATEGORY.NAME
FROM FOOD,
     ALLERGEN,
     ALLERGEN_CATEGORY
WHERE FOOD.ID = ALLERGEN.FOOD_ID
AND ALLERGEN.ALLERGEN_CATEGORY_ID = ALLERGEN_CATEGORY.ID