



/* BASE PARAMETERS */
/* DO NOT EDIT BELOW THIS LINE */
INSERT INTO PARAMETER_CATEGORY (NAME) VALUES ('Medidas Padrão');

INSERT INTO PARAMETER (MNEMONIC, NAME, TYPE, CATEGORY_ID) VALUES ('ALTURA','Altura','DOUBLE', 1);
INSERT INTO PARAMETER (MNEMONIC, NAME, TYPE, CATEGORY_ID) VALUES ('PESO','Peso','DOUBLE', 1);
INSERT INTO PARAMETER (MNEMONIC, NAME, TYPE, CATEGORY_ID) VALUES ('TAXA_DE_ATIVIDADE','Taxa de Atividade','ACTIVITY_RATE', 1);

INSERT INTO PARAMETER_CATEGORY (NAME) VALUES ('Medidas com Adipômetro');

INSERT INTO PARAMETER (MNEMONIC, NAME, TYPE, CATEGORY_ID) VALUES ('SUPRA_ILIACA','Supra Ilíaca','DOUBLE', 2);
INSERT INTO PARAMETER (MNEMONIC, NAME, TYPE, CATEGORY_ID) VALUES ('SUBESCAPULAR','Subescapular','DOUBLE', 2);
INSERT INTO PARAMETER (MNEMONIC, NAME, TYPE, CATEGORY_ID) VALUES ('COXA','Coxa','DOUBLE', 2);
INSERT INTO PARAMETER (MNEMONIC, NAME, TYPE, CATEGORY_ID) VALUES ('TRICEPS','Tríceps','DOUBLE', 2);
INSERT INTO PARAMETER (MNEMONIC, NAME, TYPE, CATEGORY_ID) VALUES ('ABDOMEN','Abdômen','DOUBLE', 2);

INSERT INTO PARAMETER_CATEGORY (NAME) VALUES ('Medidas com Fita Métrica');

INSERT INTO PARAMETER (MNEMONIC, NAME, TYPE, CATEGORY_ID) VALUES ('QUADRIL','Quadríl','DOUBLE', 3);
INSERT INTO PARAMETER (MNEMONIC, NAME, TYPE, CATEGORY_ID) VALUES ('PESCOCO','Pescoço','DOUBLE', 3);
INSERT INTO PARAMETER (MNEMONIC, NAME, TYPE, CATEGORY_ID) VALUES ('CINTURA','Cintura','DOUBLE', 3);

INSERT INTO PARAMETER_CATEGORY (NAME) VALUES ('Medidas Customizadas');





