INSERT INTO ALLERGEN_CATEGORY  (NAME) VALUES ('Lactose')
INSERT INTO ALLERGEN_CATEGORY  (NAME) VALUES ('Nozes/Amendoim')
INSERT INTO ALLERGEN_CATEGORY  (NAME) VALUES ('Peixes e Frutos do Mar')
INSERT INTO ALLERGEN_CATEGORY  (NAME) VALUES ('Ovos')
INSERT INTO ALLERGEN_CATEGORY  (NAME) VALUES ('Glúten')

