INSERT INTO HOMEMADE_MEASURE (name) VALUES ('Xícara');
INSERT INTO HOMEMADE_MEASURE (name) VALUES ('Colher de Sopa');
INSERT INTO HOMEMADE_MEASURE (name) VALUES ('Colher de Chá');
INSERT INTO HOMEMADE_MEASURE (name) VALUES ('Espumadeira');
INSERT INTO HOMEMADE_MEASURE (name) VALUES ('Copo Americano');
INSERT INTO HOMEMADE_MEASURE (name) VALUES ('Prato Fundo');
INSERT INTO HOMEMADE_MEASURE (name) VALUES ('Prato Raso');
INSERT INTO HOMEMADE_MEASURE (name) VALUES ('Fatia');