INSERT INTO MEASURE ( FOOD_ID , HOMEMADE_MEASURE_ID ,VALUE_IN_PORTION ) VALUES ( 1, 1, 1);
INSERT INTO MEASURE ( FOOD_ID , HOMEMADE_MEASURE_ID ,VALUE_IN_PORTION ) VALUES ( 1, 2, 1.5);
INSERT INTO MEASURE ( FOOD_ID , HOMEMADE_MEASURE_ID ,VALUE_IN_PORTION ) VALUES ( 2, 1, 2);
INSERT INTO MEASURE ( FOOD_ID , HOMEMADE_MEASURE_ID ,VALUE_IN_PORTION ) VALUES ( 2, 2, 0.5);
INSERT INTO MEASURE ( FOOD_ID , HOMEMADE_MEASURE_ID ,VALUE_IN_PORTION ) VALUES ( 3, 1, 2);
INSERT INTO MEASURE ( FOOD_ID , HOMEMADE_MEASURE_ID ,VALUE_IN_PORTION ) VALUES ( 3, 2, 1.5);